banking:
#    resource: "@BankingBundle/Resources/config/routing.yml"
    resource: "@BankingBundle/Controller/"
    prefix:   /banking
    type: annotation

noteboard:
    resource: "@NoteboardBundle/Resources/config/routing.yml"
    prefix:   /note

app:
    resource: '@AppBundle/Controller/'
    type: annotation
