banking:
    resource: "@BankingBundle/Resources/config/routing.yml"
    prefix:   /banking

noteboard:
    resource: "@NoteboardBundle/Resources/config/routing.yml"
    prefix:   /note

app:
    resource: '@AppBundle/Controller/'
    type: annotation
